baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Bull Traders Documentation'
theme = 'hugo-book'


[params]

  # (Optional, default docs) Specify root page to render child pages as menu.
  # Page is resoled by .GetPage function: https://gohugo.io/functions/getpage/
  # For backward compatibility you can set '*' to render all sections to menu. Acts same as '/'

  # BookMenuBundle = '/menu'
  BookSection = "*"
  BookSearch = false